/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestUnReservedBodySchema model module.
 * @module model/RequestUnReservedBodySchema
 * @version 6.0
 */
class RequestUnReservedBodySchema {
    /**
     * Constructs a new <code>RequestUnReservedBodySchema</code>.
     * @alias module:model/RequestUnReservedBodySchema
     */
    constructor() { 
        
        RequestUnReservedBodySchema.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestUnReservedBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestUnReservedBodySchema} obj Optional instance to populate.
     * @return {module:model/RequestUnReservedBodySchema} The populated <code>RequestUnReservedBodySchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestUnReservedBodySchema();

            if (data.hasOwnProperty('pin')) {
                obj['pin'] = ApiClient.convertToType(data['pin'], 'String');
            }
            if (data.hasOwnProperty('codes')) {
                obj['codes'] = ApiClient.convertToType(data['codes'], ['String']);
            }
            if (data.hasOwnProperty('bill_number')) {
                obj['bill_number'] = ApiClient.convertToType(data['bill_number'], 'String');
            }
            if (data.hasOwnProperty('bill_created_at')) {
                obj['bill_created_at'] = ApiClient.convertToType(data['bill_created_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequestUnReservedBodySchema</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequestUnReservedBodySchema</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['pin'] && !(typeof data['pin'] === 'string' || data['pin'] instanceof String)) {
            throw new Error("Expected the field `pin` to be a primitive type in the JSON string but got " + data['pin']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['codes'])) {
            throw new Error("Expected the field `codes` to be an array in the JSON data but got " + data['codes']);
        }
        // ensure the json data is a string
        if (data['bill_number'] && !(typeof data['bill_number'] === 'string' || data['bill_number'] instanceof String)) {
            throw new Error("Expected the field `bill_number` to be a primitive type in the JSON string but got " + data['bill_number']);
        }
        // ensure the json data is a string
        if (data['bill_created_at'] && !(typeof data['bill_created_at'] === 'string' || data['bill_created_at'] instanceof String)) {
            throw new Error("Expected the field `bill_created_at` to be a primitive type in the JSON string but got " + data['bill_created_at']);
        }

        return true;
    }


}



/**
 * Store pin
 * @member {String} pin
 */
RequestUnReservedBodySchema.prototype['pin'] = undefined;

/**
 * Array of 10-16 characters Got It voucher codes
 * @member {Array.<String>} codes
 */
RequestUnReservedBodySchema.prototype['codes'] = undefined;

/**
 * Bill number will apply vouchers
 * @member {String} bill_number
 */
RequestUnReservedBodySchema.prototype['bill_number'] = undefined;

/**
 * Bill creation time. Format: YYYY-MM-DD HH:MM:SS
 * @member {String} bill_created_at
 */
RequestUnReservedBodySchema.prototype['bill_created_at'] = undefined;






export default RequestUnReservedBodySchema;

