/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseCheckMultipleSchemaV60DataInnerProduct model module.
 * @module model/ResponseCheckMultipleSchemaV60DataInnerProduct
 * @version 6.0
 */
class ResponseCheckMultipleSchemaV60DataInnerProduct {
    /**
     * Constructs a new <code>ResponseCheckMultipleSchemaV60DataInnerProduct</code>.
     * @alias module:model/ResponseCheckMultipleSchemaV60DataInnerProduct
     */
    constructor() { 
        
        ResponseCheckMultipleSchemaV60DataInnerProduct.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseCheckMultipleSchemaV60DataInnerProduct</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseCheckMultipleSchemaV60DataInnerProduct} obj Optional instance to populate.
     * @return {module:model/ResponseCheckMultipleSchemaV60DataInnerProduct} The populated <code>ResponseCheckMultipleSchemaV60DataInnerProduct</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseCheckMultipleSchemaV60DataInnerProduct();

            if (data.hasOwnProperty('product_name_en')) {
                obj['product_name_en'] = ApiClient.convertToType(data['product_name_en'], 'String');
            }
            if (data.hasOwnProperty('product_name_vi')) {
                obj['product_name_vi'] = ApiClient.convertToType(data['product_name_vi'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('poscode')) {
                obj['poscode'] = ApiClient.convertToType(data['poscode'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseCheckMultipleSchemaV60DataInnerProduct</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseCheckMultipleSchemaV60DataInnerProduct</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['product_name_en'] && !(typeof data['product_name_en'] === 'string' || data['product_name_en'] instanceof String)) {
            throw new Error("Expected the field `product_name_en` to be a primitive type in the JSON string but got " + data['product_name_en']);
        }
        // ensure the json data is a string
        if (data['product_name_vi'] && !(typeof data['product_name_vi'] === 'string' || data['product_name_vi'] instanceof String)) {
            throw new Error("Expected the field `product_name_vi` to be a primitive type in the JSON string but got " + data['product_name_vi']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['poscode'] && !(typeof data['poscode'] === 'string' || data['poscode'] instanceof String)) {
            throw new Error("Expected the field `poscode` to be a primitive type in the JSON string but got " + data['poscode']);
        }
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }

        return true;
    }


}



/**
 * Product name in English
 * @member {String} product_name_en
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['product_name_en'] = undefined;

/**
 * Product name in Vietnamese
 * @member {String} product_name_vi
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['product_name_vi'] = undefined;

/**
 * Type of product
 * @member {String} type
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['type'] = undefined;

/**
 * Value of voucher
 * @member {Number} value
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['value'] = undefined;

/**
 * @member {String} poscode
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['poscode'] = undefined;

/**
 * @member {String} sku
 */
ResponseCheckMultipleSchemaV60DataInnerProduct.prototype['sku'] = undefined;






export default ResponseCheckMultipleSchemaV60DataInnerProduct;

