/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner model module.
 * @module model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
 * @version 6.0
 */
class ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner {
    /**
     * Constructs a new <code>ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner</code>.
     * @alias module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
     */
    constructor() { 
        
        ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner} obj Optional instance to populate.
     * @return {module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner} The populated <code>ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner();

            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }

        return true;
    }


}



/**
 * SKU code is redeemed for voucher
 * @member {String} sku
 */
ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.prototype['sku'] = undefined;

/**
 * SKU quantity is redeemed for voucher
 * @member {Number} quantity
 */
ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.prototype['quantity'] = undefined;

/**
 * Selling price of SKU in bill.
 * @member {Number} price
 */
ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.prototype['price'] = undefined;






export default ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner;

