/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseCheckMultipleSchemaDataInnerConditions from './ResponseCheckMultipleSchemaDataInnerConditions';
import ResponseReservedSchemaDataInnerRedemptions from './ResponseReservedSchemaDataInnerRedemptions';

/**
 * The ResponseReservedSchemaDataInner model module.
 * @module model/ResponseReservedSchemaDataInner
 * @version 1.0.3
 */
class ResponseReservedSchemaDataInner {
    /**
     * Constructs a new <code>ResponseReservedSchemaDataInner</code>.
     * @alias module:model/ResponseReservedSchemaDataInner
     */
    constructor() { 
        
        ResponseReservedSchemaDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseReservedSchemaDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseReservedSchemaDataInner} obj Optional instance to populate.
     * @return {module:model/ResponseReservedSchemaDataInner} The populated <code>ResponseReservedSchemaDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseReservedSchemaDataInner();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'Number');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
            if (data.hasOwnProperty('voucher_type')) {
                obj['voucher_type'] = ApiClient.convertToType(data['voucher_type'], 'String');
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ResponseCheckMultipleSchemaDataInnerConditions.constructFromObject(data['conditions']);
            }
            if (data.hasOwnProperty('redemptions')) {
                obj['redemptions'] = ResponseReservedSchemaDataInnerRedemptions.constructFromObject(data['redemptions']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseReservedSchemaDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseReservedSchemaDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['voucher_type'] && !(typeof data['voucher_type'] === 'string' || data['voucher_type'] instanceof String)) {
            throw new Error("Expected the field `voucher_type` to be a primitive type in the JSON string but got " + data['voucher_type']);
        }
        // validate the optional field `conditions`
        if (data['conditions']) { // data not null
          ResponseCheckMultipleSchemaDataInnerConditions.validateJSON(data['conditions']);
        }
        // validate the optional field `redemptions`
        if (data['redemptions']) { // data not null
          ResponseReservedSchemaDataInnerRedemptions.validateJSON(data['redemptions']);
        }

        return true;
    }


}



/**
 * Voucher code
 * @member {String} code
 */
ResponseReservedSchemaDataInner.prototype['code'] = undefined;

/**
 * Value of voucher
 * @member {Number} value
 */
ResponseReservedSchemaDataInner.prototype['value'] = undefined;

/**
 * State of voucher
 * @member {Number} state
 */
ResponseReservedSchemaDataInner.prototype['state'] = undefined;

/**
 * Product ID
 * @member {Number} product_id
 */
ResponseReservedSchemaDataInner.prototype['product_id'] = undefined;

/**
 * Voucher type, standard or conditional
 * @member {String} voucher_type
 */
ResponseReservedSchemaDataInner.prototype['voucher_type'] = undefined;

/**
 * @member {module:model/ResponseCheckMultipleSchemaDataInnerConditions} conditions
 */
ResponseReservedSchemaDataInner.prototype['conditions'] = undefined;

/**
 * @member {module:model/ResponseReservedSchemaDataInnerRedemptions} redemptions
 */
ResponseReservedSchemaDataInner.prototype['redemptions'] = undefined;






export default ResponseReservedSchemaDataInner;

