/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseUnReservedSchemaDataInner model module.
 * @module model/ResponseUnReservedSchemaDataInner
 * @version 1.0.2
 */
class ResponseUnReservedSchemaDataInner {
    /**
     * Constructs a new <code>ResponseUnReservedSchemaDataInner</code>.
     * @alias module:model/ResponseUnReservedSchemaDataInner
     */
    constructor() { 
        
        ResponseUnReservedSchemaDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseUnReservedSchemaDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseUnReservedSchemaDataInner} obj Optional instance to populate.
     * @return {module:model/ResponseUnReservedSchemaDataInner} The populated <code>ResponseUnReservedSchemaDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseUnReservedSchemaDataInner();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
            if (data.hasOwnProperty('voucher_type')) {
                obj['voucher_type'] = ApiClient.convertToType(data['voucher_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseUnReservedSchemaDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseUnReservedSchemaDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['voucher_type'] && !(typeof data['voucher_type'] === 'string' || data['voucher_type'] instanceof String)) {
            throw new Error("Expected the field `voucher_type` to be a primitive type in the JSON string but got " + data['voucher_type']);
        }

        return true;
    }


}



/**
 * Voucher code
 * @member {String} code
 */
ResponseUnReservedSchemaDataInner.prototype['code'] = undefined;

/**
 * Value of voucher
 * @member {Number} value
 */
ResponseUnReservedSchemaDataInner.prototype['value'] = undefined;

/**
 * Product ID
 * @member {Number} product_id
 */
ResponseUnReservedSchemaDataInner.prototype['product_id'] = undefined;

/**
 * Voucher type, standard or conditional
 * @member {String} voucher_type
 */
ResponseUnReservedSchemaDataInner.prototype['voucher_type'] = undefined;






export default ResponseUnReservedSchemaDataInner;

