/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseMarkUseMultipleSchemaDataInnerConditions model module.
 * @module model/ResponseMarkUseMultipleSchemaDataInnerConditions
 * @version 6.0
 */
class ResponseMarkUseMultipleSchemaDataInnerConditions {
    /**
     * Constructs a new <code>ResponseMarkUseMultipleSchemaDataInnerConditions</code>.
     * Include information involve with voucher type is conditional
     * @alias module:model/ResponseMarkUseMultipleSchemaDataInnerConditions
     */
    constructor() { 
        
        ResponseMarkUseMultipleSchemaDataInnerConditions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseMarkUseMultipleSchemaDataInnerConditions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseMarkUseMultipleSchemaDataInnerConditions} obj Optional instance to populate.
     * @return {module:model/ResponseMarkUseMultipleSchemaDataInnerConditions} The populated <code>ResponseMarkUseMultipleSchemaDataInnerConditions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseMarkUseMultipleSchemaDataInnerConditions();

            if (data.hasOwnProperty('redeemable_skus')) {
                obj['redeemable_skus'] = ApiClient.convertToType(data['redeemable_skus'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseMarkUseMultipleSchemaDataInnerConditions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseMarkUseMultipleSchemaDataInnerConditions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['redeemable_skus'])) {
            throw new Error("Expected the field `redeemable_skus` to be an array in the JSON data but got " + data['redeemable_skus']);
        }

        return true;
    }


}



/**
 * List of redeemable SKUs of the voucher code. For voucher type = conditional, bill number must contain at least 1 redeemable SKU of the voucher.
 * @member {Array.<String>} redeemable_skus
 */
ResponseMarkUseMultipleSchemaDataInnerConditions.prototype['redeemable_skus'] = undefined;






export default ResponseMarkUseMultipleSchemaDataInnerConditions;

