/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner from './ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner';

/**
 * The ResponseCheckMultipleSchemaV60DataInnerRedeemSku model module.
 * @module model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku
 * @version 6.0
 */
class ResponseCheckMultipleSchemaV60DataInnerRedeemSku {
    /**
     * Constructs a new <code>ResponseCheckMultipleSchemaV60DataInnerRedeemSku</code>.
     * @alias module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku
     */
    constructor() { 
        
        ResponseCheckMultipleSchemaV60DataInnerRedeemSku.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseCheckMultipleSchemaV60DataInnerRedeemSku</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku} obj Optional instance to populate.
     * @return {module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku} The populated <code>ResponseCheckMultipleSchemaV60DataInnerRedeemSku</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseCheckMultipleSchemaV60DataInnerRedeemSku();

            if (data.hasOwnProperty('redeem_sku_codes')) {
                obj['redeem_sku_codes'] = ApiClient.convertToType(data['redeem_sku_codes'], [ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner]);
            }
            if (data.hasOwnProperty('sku_redemption_value')) {
                obj['sku_redemption_value'] = ApiClient.convertToType(data['sku_redemption_value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseCheckMultipleSchemaV60DataInnerRedeemSku</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseCheckMultipleSchemaV60DataInnerRedeemSku</code>.
     */
    static validateJSON(data) {
        if (data['redeem_sku_codes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['redeem_sku_codes'])) {
                throw new Error("Expected the field `redeem_sku_codes` to be an array in the JSON data but got " + data['redeem_sku_codes']);
            }
            // validate the optional field `redeem_sku_codes` (array)
            for (const item of data['redeem_sku_codes']) {
                ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Contains redeemed SKU information
 * @member {Array.<module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner>} redeem_sku_codes
 */
ResponseCheckMultipleSchemaV60DataInnerRedeemSku.prototype['redeem_sku_codes'] = undefined;

/**
 * Actual redemption value of voucher type = redeemable_sku
 * @member {Number} sku_redemption_value
 */
ResponseCheckMultipleSchemaV60DataInnerRedeemSku.prototype['sku_redemption_value'] = undefined;






export default ResponseCheckMultipleSchemaV60DataInnerRedeemSku;

