/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner from './ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner';

/**
 * The ResponseReservedSchemaDataInnerRedemptions model module.
 * @module model/ResponseReservedSchemaDataInnerRedemptions
 * @version 1.0.2
 */
class ResponseReservedSchemaDataInnerRedemptions {
    /**
     * Constructs a new <code>ResponseReservedSchemaDataInnerRedemptions</code>.
     * Include information related to the use of the voucher (all types)
     * @alias module:model/ResponseReservedSchemaDataInnerRedemptions
     */
    constructor() { 
        
        ResponseReservedSchemaDataInnerRedemptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseReservedSchemaDataInnerRedemptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseReservedSchemaDataInnerRedemptions} obj Optional instance to populate.
     * @return {module:model/ResponseReservedSchemaDataInnerRedemptions} The populated <code>ResponseReservedSchemaDataInnerRedemptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseReservedSchemaDataInnerRedemptions();

            if (data.hasOwnProperty('redeem_sku_codes')) {
                obj['redeem_sku_codes'] = ApiClient.convertToType(data['redeem_sku_codes'], [ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner]);
            }
            if (data.hasOwnProperty('redemption_value')) {
                obj['redemption_value'] = ApiClient.convertToType(data['redemption_value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseReservedSchemaDataInnerRedemptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseReservedSchemaDataInnerRedemptions</code>.
     */
    static validateJSON(data) {
        if (data['redeem_sku_codes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['redeem_sku_codes'])) {
                throw new Error("Expected the field `redeem_sku_codes` to be an array in the JSON data but got " + data['redeem_sku_codes']);
            }
            // validate the optional field `redeem_sku_codes` (array)
            for (const item of data['redeem_sku_codes']) {
                ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Contains redeemed SKU information of the voucher (for voucher type is conditional and support sku)
 * @member {Array.<module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner>} redeem_sku_codes
 */
ResponseReservedSchemaDataInnerRedemptions.prototype['redeem_sku_codes'] = undefined;

/**
 * Actual redemption value of voucher type = conditional
 * @member {Number} redemption_value
 */
ResponseReservedSchemaDataInnerRedemptions.prototype['redemption_value'] = undefined;






export default ResponseReservedSchemaDataInnerRedemptions;

