/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseCheckMultipleSchemaV60DataInnerRedeemSku from './ResponseCheckMultipleSchemaV60DataInnerRedeemSku';

/**
 * The ResponseReservedSchemaV60DataInner model module.
 * @module model/ResponseReservedSchemaV60DataInner
 * @version 6.0
 */
class ResponseReservedSchemaV60DataInner {
    /**
     * Constructs a new <code>ResponseReservedSchemaV60DataInner</code>.
     * @alias module:model/ResponseReservedSchemaV60DataInner
     */
    constructor() { 
        
        ResponseReservedSchemaV60DataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseReservedSchemaV60DataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseReservedSchemaV60DataInner} obj Optional instance to populate.
     * @return {module:model/ResponseReservedSchemaV60DataInner} The populated <code>ResponseReservedSchemaV60DataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseReservedSchemaV60DataInner();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('voucher_type')) {
                obj['voucher_type'] = ApiClient.convertToType(data['voucher_type'], 'String');
            }
            if (data.hasOwnProperty('skus_condition_vi')) {
                obj['skus_condition_vi'] = ApiClient.convertToType(data['skus_condition_vi'], 'String');
            }
            if (data.hasOwnProperty('skus_condition_en')) {
                obj['skus_condition_en'] = ApiClient.convertToType(data['skus_condition_en'], 'String');
            }
            if (data.hasOwnProperty('redeem_sku')) {
                obj['redeem_sku'] = ResponseCheckMultipleSchemaV60DataInnerRedeemSku.constructFromObject(data['redeem_sku']);
            }
            if (data.hasOwnProperty('redeemable_skus')) {
                obj['redeemable_skus'] = ApiClient.convertToType(data['redeemable_skus'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseReservedSchemaV60DataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseReservedSchemaV60DataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['voucher_type'] && !(typeof data['voucher_type'] === 'string' || data['voucher_type'] instanceof String)) {
            throw new Error("Expected the field `voucher_type` to be a primitive type in the JSON string but got " + data['voucher_type']);
        }
        // ensure the json data is a string
        if (data['skus_condition_vi'] && !(typeof data['skus_condition_vi'] === 'string' || data['skus_condition_vi'] instanceof String)) {
            throw new Error("Expected the field `skus_condition_vi` to be a primitive type in the JSON string but got " + data['skus_condition_vi']);
        }
        // ensure the json data is a string
        if (data['skus_condition_en'] && !(typeof data['skus_condition_en'] === 'string' || data['skus_condition_en'] instanceof String)) {
            throw new Error("Expected the field `skus_condition_en` to be a primitive type in the JSON string but got " + data['skus_condition_en']);
        }
        // validate the optional field `redeem_sku`
        if (data['redeem_sku']) { // data not null
          ResponseCheckMultipleSchemaV60DataInnerRedeemSku.validateJSON(data['redeem_sku']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['redeemable_skus'])) {
            throw new Error("Expected the field `redeemable_skus` to be an array in the JSON data but got " + data['redeemable_skus']);
        }

        return true;
    }


}



/**
 * Voucher code
 * @member {String} code
 */
ResponseReservedSchemaV60DataInner.prototype['code'] = undefined;

/**
 * Voucher type, standard or redeemable_sku
 * @member {String} voucher_type
 */
ResponseReservedSchemaV60DataInner.prototype['voucher_type'] = undefined;

/**
 * Voucher SKU terms and conditions description in Vietnamese
 * @member {String} skus_condition_vi
 */
ResponseReservedSchemaV60DataInner.prototype['skus_condition_vi'] = undefined;

/**
 * Voucher SKU terms and conditions description in English
 * @member {String} skus_condition_en
 */
ResponseReservedSchemaV60DataInner.prototype['skus_condition_en'] = undefined;

/**
 * @member {module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku} redeem_sku
 */
ResponseReservedSchemaV60DataInner.prototype['redeem_sku'] = undefined;

/**
 * List of redeemable SKUs of the voucher code. For voucher type = redeemable_sku, bill number must contain at least 1 redeemable SKU of the voucher.
 * @member {Array.<String>} redeemable_skus
 */
ResponseReservedSchemaV60DataInner.prototype['redeemable_skus'] = undefined;






export default ResponseReservedSchemaV60DataInner;

