/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseReservedSchemaDataInnerRedemptions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseReservedSchemaDataInnerRedemptions', function() {
    it('should create an instance of ResponseReservedSchemaDataInnerRedemptions', function() {
      // uncomment below and update the code to test ResponseReservedSchemaDataInnerRedemptions
      //var instance = new MerchantApis.ResponseReservedSchemaDataInnerRedemptions();
      //expect(instance).to.be.a(MerchantApis.ResponseReservedSchemaDataInnerRedemptions);
    });

    it('should have the property redeemSkuCodes (base name: "redeem_sku_codes")', function() {
      // uncomment below and update the code to test the property redeemSkuCodes
      //var instance = new MerchantApis.ResponseReservedSchemaDataInnerRedemptions();
      //expect(instance).to.be();
    });

    it('should have the property redemptionValue (base name: "redemption_value")', function() {
      // uncomment below and update the code to test the property redemptionValue
      //var instance = new MerchantApis.ResponseReservedSchemaDataInnerRedemptions();
      //expect(instance).to.be();
    });

  });

}));
