/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseMarkUseMultipleSchemaV60DataInnerUsedStore();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseMarkUseMultipleSchemaV60DataInnerUsedStore', function() {
    it('should create an instance of ResponseMarkUseMultipleSchemaV60DataInnerUsedStore', function() {
      // uncomment below and update the code to test ResponseMarkUseMultipleSchemaV60DataInnerUsedStore
      //var instance = new MerchantApis.ResponseMarkUseMultipleSchemaV60DataInnerUsedStore();
      //expect(instance).to.be.a(MerchantApis.ResponseMarkUseMultipleSchemaV60DataInnerUsedStore);
    });

    it('should have the property nameVi (base name: "name_vi")', function() {
      // uncomment below and update the code to test the property nameVi
      //var instance = new MerchantApis.ResponseMarkUseMultipleSchemaV60DataInnerUsedStore();
      //expect(instance).to.be();
    });

    it('should have the property nameEn (base name: "name_en")', function() {
      // uncomment below and update the code to test the property nameEn
      //var instance = new MerchantApis.ResponseMarkUseMultipleSchemaV60DataInnerUsedStore();
      //expect(instance).to.be();
    });

  });

}));
