/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseCheckMultipleSchemaDataInner', function() {
    it('should create an instance of ResponseCheckMultipleSchemaDataInner', function() {
      // uncomment below and update the code to test ResponseCheckMultipleSchemaDataInner
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be.a(MerchantApis.ResponseCheckMultipleSchemaDataInner);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property voucherType (base name: "voucher_type")', function() {
      // uncomment below and update the code to test the property voucherType
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiry_date")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property cancelDate (base name: "cancel_date")', function() {
      // uncomment below and update the code to test the property cancelDate
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property conditions (base name: "conditions")', function() {
      // uncomment below and update the code to test the property conditions
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

    it('should have the property redemptions (base name: "redemptions")', function() {
      // uncomment below and update the code to test the property redemptions
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaDataInner();
      //expect(instance).to.be();
    });

  });

}));
