/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseUnReservedSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseUnReservedSchema', function() {
    it('should create an instance of ResponseUnReservedSchema', function() {
      // uncomment below and update the code to test ResponseUnReservedSchema
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be.a(MerchantApis.ResponseUnReservedSchema);
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property returnCode (base name: "return_code")', function() {
      // uncomment below and update the code to test the property returnCode
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property messageEn (base name: "message_en")', function() {
      // uncomment below and update the code to test the property messageEn
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property messageVi (base name: "message_vi")', function() {
      // uncomment below and update the code to test the property messageVi
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property usedStore (base name: "used_store")', function() {
      // uncomment below and update the code to test the property usedStore
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property billNumber (base name: "bill_number")', function() {
      // uncomment below and update the code to test the property billNumber
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new MerchantApis.ResponseUnReservedSchema();
      //expect(instance).to.be();
    });

  });

}));
