/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseCheckMultipleSchemaV60DataInnerProduct', function() {
    it('should create an instance of ResponseCheckMultipleSchemaV60DataInnerProduct', function() {
      // uncomment below and update the code to test ResponseCheckMultipleSchemaV60DataInnerProduct
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be.a(MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct);
    });

    it('should have the property productNameEn (base name: "product_name_en")', function() {
      // uncomment below and update the code to test the property productNameEn
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

    it('should have the property productNameVi (base name: "product_name_vi")', function() {
      // uncomment below and update the code to test the property productNameVi
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

    it('should have the property poscode (base name: "poscode")', function() {
      // uncomment below and update the code to test the property poscode
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInnerProduct();
      //expect(instance).to.be();
    });

  });

}));
