/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerchantApis);
  }
}(this, function(expect, MerchantApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseCheckMultipleSchemaV60DataInner', function() {
    it('should create an instance of ResponseCheckMultipleSchemaV60DataInner', function() {
      // uncomment below and update the code to test ResponseCheckMultipleSchemaV60DataInner
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be.a(MerchantApis.ResponseCheckMultipleSchemaV60DataInner);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property product (base name: "product")', function() {
      // uncomment below and update the code to test the property product
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property usedDate (base name: "used_date")', function() {
      // uncomment below and update the code to test the property usedDate
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiry_date")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property cancelDate (base name: "cancel_date")', function() {
      // uncomment below and update the code to test the property cancelDate
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property usedStore (base name: "used_store")', function() {
      // uncomment below and update the code to test the property usedStore
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property billNumber (base name: "bill_number")', function() {
      // uncomment below and update the code to test the property billNumber
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property voucherType (base name: "voucher_type")', function() {
      // uncomment below and update the code to test the property voucherType
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property skusConditionVi (base name: "skus_condition_vi")', function() {
      // uncomment below and update the code to test the property skusConditionVi
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property skusConditionEn (base name: "skus_condition_en")', function() {
      // uncomment below and update the code to test the property skusConditionEn
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property redeemSku (base name: "redeem_sku")', function() {
      // uncomment below and update the code to test the property redeemSku
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

    it('should have the property redeemableSkus (base name: "redeemable_skus")', function() {
      // uncomment below and update the code to test the property redeemableSkus
      //var instance = new MerchantApis.ResponseCheckMultipleSchemaV60DataInner();
      //expect(instance).to.be();
    });

  });

}));
