/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import RequestCheckMultipleBodySchema from './model/RequestCheckMultipleBodySchema';
import RequestCheckMultipleBodySchemaSkusInfoInner from './model/RequestCheckMultipleBodySchemaSkusInfoInner';
import RequestMarkUseMultipleBodySchema from './model/RequestMarkUseMultipleBodySchema';
import RequestReservedBodySchema from './model/RequestReservedBodySchema';
import RequestUnReservedBodySchema from './model/RequestUnReservedBodySchema';
import ResponseCheckMultipleSchema from './model/ResponseCheckMultipleSchema';
import ResponseCheckMultipleSchemaDataInner from './model/ResponseCheckMultipleSchemaDataInner';
import ResponseCheckMultipleSchemaDataInnerConditions from './model/ResponseCheckMultipleSchemaDataInnerConditions';
import ResponseCheckMultipleSchemaDataInnerRedemptions from './model/ResponseCheckMultipleSchemaDataInnerRedemptions';
import ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner from './model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner';
import ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore from './model/ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore';
import ResponseMarkUseMultipleSchema from './model/ResponseMarkUseMultipleSchema';
import ResponseMarkUseMultipleSchemaDataInner from './model/ResponseMarkUseMultipleSchemaDataInner';
import ResponseMarkUseMultipleSchemaDataInnerRedemptions from './model/ResponseMarkUseMultipleSchemaDataInnerRedemptions';
import ResponseReservedSchema from './model/ResponseReservedSchema';
import ResponseReservedSchemaDataInner from './model/ResponseReservedSchemaDataInner';
import ResponseReservedSchemaDataInnerRedemptions from './model/ResponseReservedSchemaDataInnerRedemptions';
import ResponseReservedSchemaUsedStore from './model/ResponseReservedSchemaUsedStore';
import ResponseUnReservedSchema from './model/ResponseUnReservedSchema';
import ResponseUnReservedSchemaDataInner from './model/ResponseUnReservedSchemaDataInner';
import GotItMerchantApi from './api/GotItMerchantApi';


/**
* SDK Technical document for Merchant APIs.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GotItMerchantSDK = require('index'); // See note below*.
* var xxxSvc = new GotItMerchantSDK.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GotItMerchantSDK.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GotItMerchantSDK.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GotItMerchantSDK.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The RequestCheckMultipleBodySchema model constructor.
     * @property {module:model/RequestCheckMultipleBodySchema}
     */
    RequestCheckMultipleBodySchema,

    /**
     * The RequestCheckMultipleBodySchemaSkusInfoInner model constructor.
     * @property {module:model/RequestCheckMultipleBodySchemaSkusInfoInner}
     */
    RequestCheckMultipleBodySchemaSkusInfoInner,

    /**
     * The RequestMarkUseMultipleBodySchema model constructor.
     * @property {module:model/RequestMarkUseMultipleBodySchema}
     */
    RequestMarkUseMultipleBodySchema,

    /**
     * The RequestReservedBodySchema model constructor.
     * @property {module:model/RequestReservedBodySchema}
     */
    RequestReservedBodySchema,

    /**
     * The RequestUnReservedBodySchema model constructor.
     * @property {module:model/RequestUnReservedBodySchema}
     */
    RequestUnReservedBodySchema,

    /**
     * The ResponseCheckMultipleSchema model constructor.
     * @property {module:model/ResponseCheckMultipleSchema}
     */
    ResponseCheckMultipleSchema,

    /**
     * The ResponseCheckMultipleSchemaDataInner model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaDataInner}
     */
    ResponseCheckMultipleSchemaDataInner,

    /**
     * The ResponseCheckMultipleSchemaDataInnerConditions model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaDataInnerConditions}
     */
    ResponseCheckMultipleSchemaDataInnerConditions,

    /**
     * The ResponseCheckMultipleSchemaDataInnerRedemptions model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaDataInnerRedemptions}
     */
    ResponseCheckMultipleSchemaDataInnerRedemptions,

    /**
     * The ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner}
     */
    ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner,

    /**
     * The ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore}
     */
    ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore,

    /**
     * The ResponseMarkUseMultipleSchema model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchema}
     */
    ResponseMarkUseMultipleSchema,

    /**
     * The ResponseMarkUseMultipleSchemaDataInner model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchemaDataInner}
     */
    ResponseMarkUseMultipleSchemaDataInner,

    /**
     * The ResponseMarkUseMultipleSchemaDataInnerRedemptions model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchemaDataInnerRedemptions}
     */
    ResponseMarkUseMultipleSchemaDataInnerRedemptions,

    /**
     * The ResponseReservedSchema model constructor.
     * @property {module:model/ResponseReservedSchema}
     */
    ResponseReservedSchema,

    /**
     * The ResponseReservedSchemaDataInner model constructor.
     * @property {module:model/ResponseReservedSchemaDataInner}
     */
    ResponseReservedSchemaDataInner,

    /**
     * The ResponseReservedSchemaDataInnerRedemptions model constructor.
     * @property {module:model/ResponseReservedSchemaDataInnerRedemptions}
     */
    ResponseReservedSchemaDataInnerRedemptions,

    /**
     * The ResponseReservedSchemaUsedStore model constructor.
     * @property {module:model/ResponseReservedSchemaUsedStore}
     */
    ResponseReservedSchemaUsedStore,

    /**
     * The ResponseUnReservedSchema model constructor.
     * @property {module:model/ResponseUnReservedSchema}
     */
    ResponseUnReservedSchema,

    /**
     * The ResponseUnReservedSchemaDataInner model constructor.
     * @property {module:model/ResponseUnReservedSchemaDataInner}
     */
    ResponseUnReservedSchemaDataInner,

    /**
    * The GotItMerchantApi service constructor.
    * @property {module:api/GotItMerchantApi}
    */
    GotItMerchantApi
};
