/**
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import RequestCheckMultipleBodySchemaV60 from './model/RequestCheckMultipleBodySchemaV60';
import RequestCheckMultipleBodySchemaV60SkusInfoInner from './model/RequestCheckMultipleBodySchemaV60SkusInfoInner';
import RequestMarkUseMultipleBodySchemaV60 from './model/RequestMarkUseMultipleBodySchemaV60';
import RequestReservedBodySchemaV60 from './model/RequestReservedBodySchemaV60';
import RequestUnReservedBodySchemaV60 from './model/RequestUnReservedBodySchemaV60';
import ResponseCheckMultipleSchemaV60 from './model/ResponseCheckMultipleSchemaV60';
import ResponseCheckMultipleSchemaV60DataInner from './model/ResponseCheckMultipleSchemaV60DataInner';
import ResponseCheckMultipleSchemaV60DataInnerProduct from './model/ResponseCheckMultipleSchemaV60DataInnerProduct';
import ResponseCheckMultipleSchemaV60DataInnerRedeemSku from './model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku';
import ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner from './model/ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner';
import ResponseCheckMultipleSchemaV60DataInnerUsedStore from './model/ResponseCheckMultipleSchemaV60DataInnerUsedStore';
import ResponseMarkUseMultipleSchemaV60 from './model/ResponseMarkUseMultipleSchemaV60';
import ResponseMarkUseMultipleSchemaV60DataInner from './model/ResponseMarkUseMultipleSchemaV60DataInner';
import ResponseMarkUseMultipleSchemaV60DataInnerUsedStore from './model/ResponseMarkUseMultipleSchemaV60DataInnerUsedStore';
import ResponseReservedSchemaV60 from './model/ResponseReservedSchemaV60';
import ResponseReservedSchemaV60DataInner from './model/ResponseReservedSchemaV60DataInner';
import ResponseReservedSchemaV60UsedStore from './model/ResponseReservedSchemaV60UsedStore';
import ResponseUnReservedSchemaV60 from './model/ResponseUnReservedSchemaV60';
import MerchantApiV60Api from './api/MerchantApiV60Api';


/**
* Technical document APIs for Merchant APIs.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MerchantApis = require('index'); // See note below*.
* var xxxSvc = new MerchantApis.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MerchantApis.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MerchantApis.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MerchantApis.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 6.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The RequestCheckMultipleBodySchemaV60 model constructor.
     * @property {module:model/RequestCheckMultipleBodySchemaV60}
     */
    RequestCheckMultipleBodySchemaV60,

    /**
     * The RequestCheckMultipleBodySchemaV60SkusInfoInner model constructor.
     * @property {module:model/RequestCheckMultipleBodySchemaV60SkusInfoInner}
     */
    RequestCheckMultipleBodySchemaV60SkusInfoInner,

    /**
     * The RequestMarkUseMultipleBodySchemaV60 model constructor.
     * @property {module:model/RequestMarkUseMultipleBodySchemaV60}
     */
    RequestMarkUseMultipleBodySchemaV60,

    /**
     * The RequestReservedBodySchemaV60 model constructor.
     * @property {module:model/RequestReservedBodySchemaV60}
     */
    RequestReservedBodySchemaV60,

    /**
     * The RequestUnReservedBodySchemaV60 model constructor.
     * @property {module:model/RequestUnReservedBodySchemaV60}
     */
    RequestUnReservedBodySchemaV60,

    /**
     * The ResponseCheckMultipleSchemaV60 model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60}
     */
    ResponseCheckMultipleSchemaV60,

    /**
     * The ResponseCheckMultipleSchemaV60DataInner model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60DataInner}
     */
    ResponseCheckMultipleSchemaV60DataInner,

    /**
     * The ResponseCheckMultipleSchemaV60DataInnerProduct model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60DataInnerProduct}
     */
    ResponseCheckMultipleSchemaV60DataInnerProduct,

    /**
     * The ResponseCheckMultipleSchemaV60DataInnerRedeemSku model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSku}
     */
    ResponseCheckMultipleSchemaV60DataInnerRedeemSku,

    /**
     * The ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner}
     */
    ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner,

    /**
     * The ResponseCheckMultipleSchemaV60DataInnerUsedStore model constructor.
     * @property {module:model/ResponseCheckMultipleSchemaV60DataInnerUsedStore}
     */
    ResponseCheckMultipleSchemaV60DataInnerUsedStore,

    /**
     * The ResponseMarkUseMultipleSchemaV60 model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchemaV60}
     */
    ResponseMarkUseMultipleSchemaV60,

    /**
     * The ResponseMarkUseMultipleSchemaV60DataInner model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchemaV60DataInner}
     */
    ResponseMarkUseMultipleSchemaV60DataInner,

    /**
     * The ResponseMarkUseMultipleSchemaV60DataInnerUsedStore model constructor.
     * @property {module:model/ResponseMarkUseMultipleSchemaV60DataInnerUsedStore}
     */
    ResponseMarkUseMultipleSchemaV60DataInnerUsedStore,

    /**
     * The ResponseReservedSchemaV60 model constructor.
     * @property {module:model/ResponseReservedSchemaV60}
     */
    ResponseReservedSchemaV60,

    /**
     * The ResponseReservedSchemaV60DataInner model constructor.
     * @property {module:model/ResponseReservedSchemaV60DataInner}
     */
    ResponseReservedSchemaV60DataInner,

    /**
     * The ResponseReservedSchemaV60UsedStore model constructor.
     * @property {module:model/ResponseReservedSchemaV60UsedStore}
     */
    ResponseReservedSchemaV60UsedStore,

    /**
     * The ResponseUnReservedSchemaV60 model constructor.
     * @property {module:model/ResponseUnReservedSchemaV60}
     */
    ResponseUnReservedSchemaV60,

    /**
    * The MerchantApiV60Api service constructor.
    * @property {module:api/MerchantApiV60Api}
    */
    MerchantApiV60Api
};
